# travis-ci.org configuration
# 
language: perl
perl:
    - "5.22"
install:
    - cpanm install --quiet --notest BerkeleyDB
    - cpanm install --quiet --notest Net::Server::Multiplex
script:
    - test/test.pl
