# travis-ci.org configuration
# 
language: perl
perl:
    - "5.22"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libdb libdb-dev
install:
    - cpanm install --quiet --notest BerkeleyDB
    - cpanm install --quiet --notest Net::Server::Multiplex
    - cpanm install --quiet --notest NetAddr::IP
    - cpanm install --quiet --notest File::Slurper
script:
    - test/test.pl
