# travis-ci.org configuration
# 
language: perl
sudo: false
perl:
    - "5.20"
addons:
    apt:
        packages:
            - libdb-dev
install:
    - cpanm install --quiet --notest BerkeleyDB
    - cpanm install --quiet --notest Net::Server::Multiplex
    - cpanm install --quiet --notest NetAddr::IP
    - cpanm install --notest File::Slurper
script:
    - ls -lR $HOME/perl5
    - env
    - test/test.pl
